name: 'SuperPointNetBn'
descriptor_dim: &DIM 256
parameters:
  max_keypoints: 2048
  descriptor_dim: *DIM
  nms_kernel: 9
  remove_borders_size: 4
  keypoint_threshold: 0.005
  weights: './models/superglue/weights/superpoint_kitti_50000_checkpoint.pth.tar'
