gpus: [ 0 ]
data:
  root_path: /host_Data/Data/MegaDepth/MegaDepth
  train_list_path: ./assets/subset-20-20-train.txt
  val_list_path: ./assets/subset-20-20-val.txt
  test_list_path: ./assets/subset-20-20-val.txt

  batch_size_per_gpu: 2
  dataloader_workers_per_gpu: 4
  target_size: [ 960, 720 ]
  val_max_pairs_per_scene: 25
  train_pairs_overlap: [0.15, 0.7]

logging:
  root_path: '/host_Data/Data/MegaDepth/MegaDepth/extracted_features/phoenix3'
  name: 'Superpoint_960_720'
  train_logs_steps: 50

train:
  epochs: 2
  steps_per_epoch: 750
  grad_clip: 10.0
  precision: 32
  gt_positive_threshold: 2
  gt_negative_threshold: 7
  margin: null
  nll_weight: 1.0
  metric_weight: 0.0
  lr: 1.0e-4
  scheduler_gamma: 0.999994
  augmentations:
    name: 'none'

evaluation:
  epipolar_dist_threshold: 5.0e-4
  camera_auc_thresholds: [5.0, 10.0, 20.0]
  camera_auc_ransac_inliers_threshold: 1.0

inference:
  match_threshold: 0.2

superglue:
  laf_to_sideinfo_method: 'none'
  positional_encoding:
    hidden_layers_sizes: [32, 64, 128]
  attention_gnn:
    num_stages: 9
    num_heads: 4
    attention: 'softmax'
    use_offset: False
  dustbin_score_init: 1.0
  otp:
    num_iters: 20
    reg: 1.0
  residual: True
