gpus: [ 0 ]
data:
  root_path: /host_Data/Data/acrobat/acrobat_train_x5/
  train_list_path: ./assets/subset-10-20-acrobat-train.txt
  val_list_path: ./assets/subset-10-20-acrobat-val.txt
  test_list_path: ./assets/subset-10-20-acrobat-val.txt
  features_dir: '/host_Data/Data/MegaDepth/MegaDepth/extracted_features/phoenix3/SuperPointNet_960_720'
  max_keypoints: 1024

  batch_size_per_gpu: 1
  dataloader_workers_per_gpu: 1
  target_size: [ 960, 720 ]
  val_max_pairs_per_scene: 10
  train_pairs_overlap: [0.15, 0.7]

logging:
  root_path: '/host_Data/Data/MegaDepth/MegaDepth/extracted_features/phoenix3'
  name: 'SuperPointNet_960_720_preextracted'
  train_logs_steps: 10

train:
  epochs: 10
  steps_per_epoch: 20
  grad_clip: 10.0
  precision: 32
  gt_positive_threshold: 2
  gt_negative_threshold: 7
  margin: null
  nll_weight: 1.0
  metric_weight: 0.0
  lr: 1.0e-4
  scheduler_gamma: 0.999994
  augmentations:
    name: 'none'
  use_cached_features: True

evaluation:
  epipolar_dist_threshold: 5.0e-4
  camera_auc_thresholds: [5.0, 10.0, 20.0]
  camera_auc_ransac_inliers_threshold: 1.0

inference:
  match_threshold: 0.2

superglue:
  laf_to_sideinfo_method: 'none'
  positional_encoding:
    hidden_layers_sizes: [32, 64, 128]
  attention_gnn:
    num_stages: 9
    num_heads: 4
    attention: 'softmax'
    use_offset: False
  dustbin_score_init: 1.0
  otp:
    num_iters: 20
    reg: 1.0
  residual: True
